{% set name = "aiapy" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiapy-{{ version }}.tar.gz
  sha256: e6c4fab8769ae904284ab89f419bc6ba3d776f3d581fcebe9e2be31e1727527f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - importlib_resources
    - python >=3.8
    - sunpy >=4.0.4

test:
  requires:
    - pip
    - pytest-astropy
  imports:
    - aiapy
    - aiapy.calibrate
    - aiapy.psf
    - aiapy.response
    - aiapy.util
  commands:
    - pip check
    - pytest --pyargs aiapy --remote-data=any

about:
  home: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy
  summary: Python package for AIA analysis.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
    - wtbarnes
