{% set name = "aiapy" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiapy-{{ version }}.tar.gz
  sha256: 27f7cd1b43ea1bab8aa8f14b81d0017e1c5935c3294c24bf082091a494f4b81a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools_scm
  run:
    - python >=3.10
    - sunpy >=6.0.0
    - packaging
    - drms
    - astropy
    - numpy
    - pyerfa
    - parfive

test:
  requires:
    - pip
    - pytest-astropy
  commands:
    - pytest --pyargs aiapy --remote-data=any

about:
  home: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy
  summary: Python package for AIA analysis.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
    - wtbarnes
