{% set name = "aiapy" %}
{% set version = "0.11.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiapy-{{ version }}.tar.gz
  sha256: b8284bb5fc075d88bfd721cf633d056b02051cbe0a65e02d6fc70382d0c41286

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - sunpy >=6.0.0
    - packaging
    - drms
    - astropy-base
    - numpy
    - pyerfa
    - parfive

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest-astropy
  commands:
    - pytest --pyargs aiapy --remote-data=none

about:
  home: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy
  summary: Python package for AIA analysis.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
    - wtbarnes
