{% set name = "aiapy" %}
{% set version = "0.7.2.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiapy-{{ version }}.tar.gz
  sha256: ce6b8e66a46886bc12706e28583abeb54f6e26704f81032adef3772aa4c8da51

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - importlib_resources
    - python >=3.8
    - sunpy >=4.0.4

test:
  requires:
    - pip
    - pytest-astropy
  imports:
    - aiapy
    - aiapy.calibrate
    - aiapy.psf
    - aiapy.response
    - aiapy.util
  commands:
    - pip check
    - pytest --pyargs aiapy --remote-data=any

about:
  home: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy
  summary: Python package for AIA analysis.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
    - wtbarnes
