{% set name = "aiapy" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiapy-{{ version }}.tar.gz
  sha256: aa8e85ced38641f10e7cfa91ee302184a0736ef247f0bbc926d24997db9065ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools_scm
  run:
    - importlib_resources
    - python >=3.10
    - sunpy >=5.0.0

test:
  requires:
    - pip
    - pytest-astropy
  imports:
    - aiapy
    - aiapy.calibrate
    - aiapy.psf
    - aiapy.response
    - aiapy.util
  commands:
    - pytest --pyargs aiapy --remote-data=any

about:
  home: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy
  summary: Python package for AIA analysis.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
    - wtbarnes
